name: ecgo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.6
  google_fonts: ^6.1.0
  responsive_framework: ^1.1.1
  smooth_page_indicator: ^1.1.0
  google_maps: ^6.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
